const translations = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.candidates": "Candidates",
    "nav.companies": "Companies",
    "hero.title": "You found the filler text~",
    "hero.subtitle": "Find Your <span class=\"text-lilac-400\">Desired Job/Employee</span>",
    "hero.description": "Connecting Professionals with Companies",
    "search_placeholder": "Search for candidates or companies...",
    "search_aria": "Search candidates or companies",
    "candidate_recommendations": "Candidate Recommendations",
    "featured_companies": "Featured Companies",
    "see_more": "See More",
    "view_profile": "View Profile",
    "view_company": "View Company",
    "software_engineer": "Software Engineer",
    "marketing_director": "Marketing Director",
    "product_manager": "Product Manager",
    "ux_designer": "UX Designer",
    "information_technology": "Information Technology",
    "creative_agency": "Creative Agency",
    "renewable_energy": "Renewable Energy",
    "healthcare": "Healthcare",
    "cv_download": "Download CV",
    "employee_details": "Employee Details",
    "employee_full_name": "Full Name",
    "employee_birth_date": "Birth Date",
    "employee_location": "Location",
    "employee_employment_status": "Employment Status",
    "employee_contact_email": "Contact Email",
    "employee_biodata": "Biodata",
    "employee_highlights": "Employee Highlights",
    "hobbies": "Hobbies",
    "company_details": "Company Details",
    "company_full_name": "Company Name",
    "company_foundation_date": "Foundation Date",
    "company_hq_location": "HQ Location",
    "company_size": "Company Size",
    "company_business_email": "Business Email",
    "company_biodata": "Company Description",
    "members": "Members",
    "services": "Our Services",
    "members_nav": "Employees",
    "education": "Education",
    "experience": "Experience",
    "skills": "Skills",
    "employee_profile_settings": "My Profile",
    "employee_logout": "Logout",
    "skills_nav": "Skills",
    "education_nav": "Education",
    "chat_nav": "Chat",
    "services_nav": "Services",
    "candidates.find_talented": "Find <span class=\"text-lilac-400\">Talented Candidates</span>",
    "candidates.browse_description": "Browse through our network of skilled professionals ready for their next opportunity",
    "search.candidate_placeholder": "Search by name, skills, or job title...",
    "search.aria_label": "Search candidates",
    "search.company_placeholder": "Search by company name, industry, or location...",
    "search.company_aria": "Search companies",
    "filter.location": "Location",
    "filter.job_type": "Job Type",
    "filter.industry": "Industry",
    "filter.all_locations": "All Indonesia",
    "filter.all_job_types": "All Job Types",
    "filter.all_industries": "All Industries",
    "filter.company_size": "Company Size",
    "filter.all_sizes": "All Sizes",
    "filter.startup": "Startup",
    "filter.small": "Small (1-50)",
    "filter.medium": "Medium (51-200)",
    "filter.large": "Large (201+)",
    "filter.enterprise": "Enterprise (1000+)",
    "filter.technology": "Technology",
    "filter.finance": "Finance",
    "filter.healthcare": "Healthcare",
    "filter.education": "Education",
    "filter.marketing": "Marketing",
    "filter.hospitality": "Hospitality",
    "filter.manufacturing": "Manufacturing",
    "filter.retail": "Retail",
    "filter.government": "Government",
    "filter.food_beverage": "Food and Beverages",
    "filter.construction": "Construction",
    "filter.all_provinces": "All Provinces",
    "filter.city": "City/District",
    "filter.all_cities": "All Cities/Districts",
    "filter.province": "Province",
    "button.apply_filters": "Apply Filters",
    "button.reset": "Reset",
    "candidates.available": "Available Candidates",
    "candidates.showing": "Showing",
    "candidates.of": "of",
    "candidates.found": "candidates",
    "candidates.pagination.previous": "Previous",
    "candidates.pagination.next": "Next",
    "companies.featured": "Featured Companies",
    "companies.showing": "Showing",
    "companies.of": "of",
    "companies.found": "companies",
    "employees": "employees",
    "open_roles": "open roles",
    "cta.cant_find": "Can't Find What You're Looking For?",
    "cta.help_text": "Let us help you find the perfect candidate. Our recruitment specialists can source and screen candidates tailored to your specific needs.",
    "cta.request_search": "Request Talent Search",
    "companies.title": "Explore <span class=\"text-lilac-400\">Top Companies</span>",
    "companies.description": "Discover leading companies hiring through our platform and find your next career opportunity",
    "hero.about": "About <span class=\"text-lilac-400\">Ruang Kerja</span>",
    "hero.about_description": "Connecting professionals with Opportunities",
    "about.story_title": "Our Story",
    "about.story_content": "Founded in 2025, RuangKerja began as a small team of Informatics Student",
    "about.story_mission": "Our mission is to create meaningful connections between professionals and companies, making the hiring process more efficient, transparent, and human-centered.",
    "about.values_title": "Our Core Values",
    "about.value1_title": "Integrity",
    "about.value1_content": "We believe in transparency and honesty in all our interactions, building trust with both candidates and employers.",
    "about.value2_title": "Innovation",
    "about.value2_content": "We continuously improve our platform to provide better matching algorithms and user experiences.",
    "about.value3_title": "Community",
    "about.value3_content": "We foster a supportive network where professionals can grow and companies can find the perfect talent.",
    "about.team_title": "Meet Our Team",
    "about.team1_position": "Backend",
    "about.team2_position": "Frontend",
    "about.team3_position": "Team Lead",
    "about.team4_position": "Frontend",
    "about.stats_title": "By The Numbers",
    "about.stat1_title": "Professionals",
    "about.stat1_content": "Talented individuals in our network",
    "about.stat2_title": "Companies",
    "about.stat2_content": "Trusting us with their hiring needs",
    "about.stat3_title": "Jobs Posted",
    "about.stat3_content": "Of candidates placed in suitable roles",
    "cta.title": "Want your Company Featured?",
    "cta.description": "Join thousands of companies attracting top talent through our platform.",
    "cta.button": "List Your Company",
    "footer.company_description": "RuangKerja connects top talent with leading companies across Indonesia. Our platform makes hiring simple, efficient, and effective.",
    "footer.for_candidates": "For Candidates",
    "footer.browse_jobs": "Browse Jobs",
    "footer.create_profile": "Create Profile",
    "footer.career_resources": "Career Resources",
    "footer.salary_calculator": "Salary Calculator",
    "footer.for_employers": "For Employers",
    "footer.post_job": "Post a Job",
    "footer.browse_candidates": "Browse Candidates",
    "footer.recruiting_solutions": "Recruiting Solutions",
    "footer.pricing": "Pricing",
    "footer.company": "Company",
    "footer.about_us": "About Us",
    "footer.contact": "Contact",
    "footer.privacy_policy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.copyright": "© 2023 RuangKerja. All rights reserved.",
    "footer.privacy_link": "Privacy",
    "footer.terms_link": "Terms",
    "footer.sitemap": "Sitemap",
    "footer.cookie_policy": "Cookie Policy",
    "footer.socials": "Our Socials",
    "footer.contact": "Contact Us",
    "footer.company_description": "RuangKerja connects top talent with leading companies across Indonesia. Our platform makes hiring simple, efficient, and effective.",
    "profile.my_profile": "My Profile",
    "profile.logout": "Logout",
    "role.selection": "Continue as",
    "role.employee": "<i class=\"fas fa-user mr-2\"></i> A Employee",
    "role.company": "<i class=\"fas fa-building mr-2\"></i> A Company",
    "role.employee.registration": "Employee Registration",
    "role.employee.full_name": "Full Name",
    "role.employee.email": "Contact Email",
    "role.employee.birth_date": "Birth Date",
    "role.employee.city": "City",
    "role.employee.job_type": "Job Type",
    "role.employee.industry": "Industry",
    "role.employee.employment_status": "Employment Status",
  },
  id: {
    "nav.home": "Beranda",
    "nav.about": "Tentang",
    "nav.candidates": "Kandidat",
    "nav.companies": "Perusahaan",
    "cv_download": "Unduh CV",
    "hero.title": "Kamu menemukan teks pengisi~",
    "hero.subtitle": "Temukan <span class=\"text-lilac-400\">Pekerjaan/Karyawan yang Diinginkan</span> Anda",
    "hero.description": "Menghubungkan Profesional dengan Perusahaan",
    "search_placeholder": "Cari kandidat atau perusahaan...",
    "search_aria": "Cari kandidat atau perusahaan",
    "search.company_placeholder": "Cari berdasarkan nama perusahaan, industri, atau lokasi...",
    "search.company_aria": "Cari perusahaan",
    "candidate_recommendations": "Rekomendasi Kandidat",
    "featured_companies": "Perusahaan Unggulan",
    "see_more": "Lihat Selengkapnya",
    "view_profile": "Lihat Profil",
    "view_company": "Lihat Perusahaan",
    "software_engineer": "Insinyur Perangkat Lunak",
    "marketing_director": "Direktur Pemasaran",
    "product_manager": "Manajer Produk",
    "ux_designer": "Desainer UX",
    "information_technology": "Teknologi Informasi",
    "creative_agency": "Agensi Kreatif",
    "renewable_energy": "Energi Terbarukan",
    "healthcare": "Kesehatan",
    "employee_details": "Detail Karyawan",
    "employee_full_name": "Nama Lengkap",
    "employee_birth_date": "Tanggal Lahir",
    "employee_location": "Lokasi",
    "employee_employment_status": "Status Pekerjaan",
    "employee_contact_email": "Email Kontak",
    "employee_biodata": "Biodata",
    "employee_highlights": "Sorotan Karyawan",
    "hobbies": "Hobi",
    "company_details": "Detail Perusahaan",
    "company_full_name": "Nama Lengkap",
    "company_foundation_date": "Tanggal Didirikan",
    "company_hq_location": "Lokasi Kantor Pusat",
    "company_size": "Jumlah Karyawan",
    "company_business_email": "Email Bisnis",
    "company_biodata": "Deskripsi Perusahaan",
    "members": "Karyawan",
    "members_nav": "Karyawan",
    "education": "Pendidikan",
    "experience": "Pengalaman",
    "skills": "Keterampilan",
    "services": "Layanan",
    "employee_profile_settings": "Profil Saya",
    "employee_logout": "Keluar",
    "skills_nav": "Keterampilan",
    "education_nav": "Pendidikan",
    "chat_nav": "Obrolan",
    "services_nav": "Layanan",
    "candidates.find_talented": "Temukan <span class=\"text-lilac-400\">Kandidat Berbakat</span>",
    "candidates.browse_description": "Jelajahi jaringan profesional terampil kami yang siap untuk peluang berikutnya",
    "search.candidate_placeholder": "Cari berdasarkan nama, keterampilan, atau jabatan...",
    "search.aria_label": "Cari kandidat",
    "filter.location": "Lokasi",
    "filter.job_type": "Jenis Pekerjaan",
    "filter.industry": "Industri",
    "filter.all_locations": "Semua Indonesia",
    "filter.all_job_types": "Semua Jenis Pekerjaan",
    "filter.all_industries": "Semua Industri",
    "filter.company_size": "Ukuran Perusahaan",
    "filter.all_sizes": "Semua Ukuran",
    "filter.startup": "Startup",
    "filter.small": "Kecil (1-50)",
    "filter.medium": "Sedang (51-200)",
    "filter.large": "Besar (201+)",
    "filter.enterprise": "Perusahaan Besar (1000+)",
    "filter.technology": "Teknologi",
    "filter.finance": "Keuangan",
    "filter.healthcare": "Kesehatan",
    "filter.education": "Pendidikan",
    "filter.marketing": "Pemasaran",
    "filter.hospitality": "Perhotelan",
    "filter.manufacturing": "Manufaktur",
    "filter.retail": "Ritel",
    "filter.government": "Pemerintah",
    "filter.food_beverage": "Makanan dan Minuman",
    "filter.construction": "Konstruksi",
    "filter.all_provinces": "Semua Provinsi",
    "filter.city": "Kota/Kabupaten",
    "filter.all_cities": "Semua Kota/Kabupaten",
    "filter.province": "Provinsi",
    "button.apply_filters": "Terapkan Filter",
    "button.reset": "Atur Ulang",
    "candidates.available": "Kandidat Tersedia",
    "candidates.showing": "Menampilkan",
    "candidates.of": "dari",
    "candidates.found": "kandidat",
    "candidates.pagination.previous": "Sebelumnya",
    "candidates.pagination.next": "Selanjutnya",
    "companies.featured": "Perusahaan Unggulan",
    "companies.showing": "Menampilkan",
    "companies.of": "dari",
    "companies.found": "perusahaan",
    "employees": "karyawan",
    "open_roles": "role terbuka",
    "cta.cant_find": "Tidak Menemukan Yang Anda Cari?",
    "cta.help_text": "Biarkan kami membantu Anda menemukan kandidat yang sempurna. Spesialis rekrutmen kami dapat mencari dan menyaring kandidat yang disesuaikan dengan kebutuhan spesifik Anda.",
    "cta.request_search": "Minta Pencarian Talenta",
    "companies.title": "Jelajahi <span class=\"text-lilac-400\">Perusahaan Teratas</span>",
    "companies.description": "Jelajahi perusahaan terkemuka yang merekrut melalui platform kami dan temukan peluang karir berikutnya.",
    "hero.about": "Tentang <span class=\"text-lilac-400\">Ruang Kerja</span>",
    "hero.about_description": "Menghubungkan profesional dengan peluang",
    "about.story_title": "Kisah Kami",
    "about.story_content": "Didirikan pada tahun 2025, RuangKerja dimulai sebagai tim kecil Mahasiswa Informatika",
    "about.story_mission": "Misi kami adalah menciptakan koneksi yang berarti antara profesional dan perusahaan, membuat proses perekrutan lebih efisien, transparan, dan berfokus pada manusia.",
    "about.values_title": "Nilai Inti Kami",
    "about.value1_title": "Integritas",
    "about.value1_content": "Kami percaya pada transparansi dan kejujuran dalam semua interaksi kami, membangun kepercayaan dengan kandidat dan pemberi kerja.",
    "about.value2_title": "Inovasi",
    "about.value2_content": "Kami terus meningkatkan platform kami untuk menyediakan algoritma pencocokan dan pengalaman pengguna yang lebih baik.",
    "about.value3_title": "Komunitas",
    "about.value3_content": "Kami mendorong jaringan yang mendukung di mana profesional dapat berkembang dan perusahaan dapat menemukan talenta yang sempurna.",
    "about.team_title": "Temui Tim Kami",
    "about.team1_position": "Backend",
    "about.team2_position": "Frontend",
    "about.team3_position": "Pemimpin Tim",
    "about.team4_position": "Frontend",
    "about.stats_title": "Menurut Angka",
    "about.stat1_title": "Profesional",
    "about.stat1_content": "Individu berbakat dalam jaringan kami",
    "about.stat2_title": "Perusahaan",
    "about.stat2_content": "Percaya pada kami untuk kebutuhan perekrutan mereka",
    "about.stat3_title": "Lowongan Diterbitkan",
    "about.stat3_content": "Dari kandidat yang ditempatkan dalam peran yang sesuai",
    "cta.title": "Ingin Perusahaan Anda Ditampilkan?",
    "cta.description": "Bergabunglah dengan ribuan perusahaan yang menarik talenta terbaik melalui platform kami.",
    "cta.button": "Daftarkan Perusahaan Anda",
    "footer.company_description": "RuangKerja menghubungkan talenta terbaik dengan perusahaan terkemuka di seluruh Indonesia. Platform kami membuat perekrutan menjadi sederhana, efisien, dan efektif.",
    "footer.for_candidates": "Untuk Kandidat",
    "footer.browse_jobs": "Jelajahi Lowongan",
    "footer.create_profile": "Buat Profil",
    "footer.career_resources": "Sumber Karir",
    "footer.salary_calculator": "Kalkulator Gaji",
    "footer.for_employers": "Untuk Pemberi Kerja",
    "footer.post_job": "Posting Lowongan",
    "footer.browse_candidates": "Jelajahi Kandidat",
    "footer.recruiting_solutions": "Solusi Rekrutmen",
    "footer.pricing": "Harga",
    "footer.company": "Perusahaan",
    "footer.about_us": "Tentang Kami",
    "footer.contact": "Kontak",
    "footer.privacy_policy": "Kebijakan Privasi",
    "footer.terms": "Ketentuan Layanan",
    "footer.copyright": "© 2023 RuangKerja. Seluruh hak cipta dilindungi.",
    "footer.privacy_link": "Privasi",
    "footer.terms_link": "Ketentuan",
    "footer.sitemap": "Peta Situs",
    "footer.cookie_policy": "Kebijakan Cookie",
    "footer.socials": "Media Sosial",
    "footer.contact": "Hubungi Kami",
    "footer.company_description": "RuangKerja menghubungkan talenta terbaik dengan perusahaan terkemuka di seluruh Indonesia. Platform kami membuat perekrutan menjadi sederhana, efisien, dan efektif.",
    "profile.my_profile": "Profil Saya",
    "profile.logout": "Keluar",
    "role.selection": "Lanjutkan sebagai",
    "role.employee": "<i class=\"fas fa-user mr-2\"></i> Seorang Karyawan",
    "role.company": "<i class=\"fas fa-building mr-2\"></i> Sebuah Perusahaan",
    "role.employee.registration": "Pendaftaran Karyawan",
    "role.employee.full_name": "Nama Lengkap",
    "role.employee.email": "Email Kontak",
    "role.employee.birth_date": "Tanggal Lahir",
    "role.employee.city": "Kota",
    "role.employee.job_type": "Jenis Pekerjaan",
    "role.employee.industry": "Industri",
    "role.employee.employment_status": "Status Pekerjaan",
  }
};

function setLanguage(lang) {
  // Basic text
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    el.textContent = translations[lang][key] || key;
  });

  // Placeholder
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    const key = el.getAttribute("data-i18n-placeholder");
    el.setAttribute("placeholder", translations[lang][key] || key);
  });

  // Aria-label
  document.querySelectorAll("[data-i18n-aria]").forEach(el => {
    const key = el.getAttribute("data-i18n-aria");
    el.setAttribute("aria-label", translations[lang][key] || key);
  });

  // HTML (for rich content like spans)
  document.querySelectorAll("[data-i18n-html]").forEach(el => {
    const key = el.getAttribute("data-i18n-html");
    el.innerHTML = translations[lang][key] || key;
  });

  localStorage.setItem("lang", lang);
}

window.addEventListener("DOMContentLoaded", () => {
  const lang = localStorage.getItem("lang") || "en";
  setLanguage(lang);

  const selector1 = document.getElementById("language-selector");
  const selector2 = document.getElementById("language-selector-mobile");
  const selector3 = document.getElementById("language-selector-employee");

  if (selector1) {
    selector1.value = lang;
    selector1.addEventListener("change", e => {
      setLanguage(e.target.value);
      // Sync other selectors
      if (selector2) selector2.value = e.target.value;
      if (selector3) selector3.value = e.target.value;
    });
  }

  if (selector2) {
    selector2.value = lang;
    selector2.addEventListener("change", e => {
      setLanguage(e.target.value);
      // Sync other selectors
      if (selector1) selector1.value = e.target.value;
      if (selector3) selector3.value = e.target.value;
    });
  }

  if (selector3) {
    selector3.value = lang;
    selector3.addEventListener("change", e => {
      setLanguage(e.target.value);
      // Sync other selectors
      if (selector1) selector1.value = e.target.value;
      if (selector2) selector2.value = e.target.value;
    });
  }
});
